### PR TITLE
Update download links and documentation for 2.7

### PR DESCRIPTION
**Pull request by aserdean**
This patch updates the links, documentation and scripts for the certified
version of OVS 2.7.

Signed-off-by: Alin Gabriel Serdean <aserdean@cloudbasesolutions.com>

### CODE REVIEW

**Comment by aserdean** [comment]
@pires yes NAT is here :)

**Comment by pires** [comment]
Not sure if anyone's paying attention to this so pinging nice gentlemen @ikester and @alexbrand.

**Comment by ikester** [comment]
Thanks @pires. CCing @bsteciuk.

**Comment by bsteciuk** [comment]
@pires @ikester I've been in contact with @aserdean, and I'm on it.  This is part of updating this demo to K8S 1.7.2 and OVS 2.7.  I've tested out the updated implementation, and am finishing up the updates to README's for the rest of it.  Plan is to pull this in with my changes tomorrow so both Linux and Windows OVS versions match.

**Comment by pires** [comment]
@bsteciuk I strongly suggest going w/ Kubernetes 1.7.3, particularly because of a nil-pointer bug in kube-proxy that affects versions 1.7.x prior to 1.7.3.

On a sidenote, I'm glad Apprenda is keeping this as it's still the best option when it comes to people using Kubernetes for Windows workloads. 👏

**Comment by bsteciuk** [comment]
These changes have been put into PR #24 with one minor change - the MSI install was moved a little later in the process as it required the Containers Windows Feature, which is installed with docker.

**Comment by bsteciuk** [comment]
These changes were cherry picked in ( commit 7d76e7080e82b56b4aef0a0cf35c67ad0efeca8d ).  Closing PR here.  Thanks!

**Pull request closed without merging**
